name: Build and deploy ASP.Net Core app to Azure Web App - quantai-be2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'  # .NET 7 sürümü

      # Global dotnet-ef aracını yükle
      - name: Install Entity Framework Core Tools globally
        run: dotnet tool install --global dotnet-ef --version 7

      # Yüklenen dotnet araçlarını PATH'e ekle
      - name: Add .NET Core tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Projeyi build et
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Projeyi publish et
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # Yayınlanan uygulamayı deployment için artifact olarak yükle
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Build job'dan artifact'i indir
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      # Azure Web App'e deploy et
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quantai-be2'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6A87B59B62D94C0AA4E01C20EA14F051 }}

      # Veritabanı migration'larını uygula
      - name: Apply EF Migrations to Azure SQL Database
        run: dotnet ef database update --no-build
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
